apiVersion: batch/v1
kind: Job
metadata:
  name: db-bridge
spec:
  template:
    spec:
      containers:
        - name: proteus-image
          image: ospproteus/proteus-image
          env:
            - name: DB_URI
              value: "mongodb+srv://proteus:codesmith-proteus@cluster-prometheus-metr.xs8xprx.mongodb.net/?retryWrites=true&w=majority"
            - name: SERVICE_IP
              value: "http://10.100.151.71:80"
          command: ["npm", "start"]
      restartPolicy: OnFailure
