GET http://localhost:9090/api/v1/label/job_name/values
Content-Type: application/json

#####
GET http://localhost:9090/api/v1/query?query={cronjob="hellocron-job"}
Content-Type: application/json

#####
 GET http://localhost:9090/api/v1/query?query={job_name=~"crontest-.*", __name__="kube_job_created"}[30m]
Content-Type: application/json

#####
GET http://localhost:9090/api/v1/query?query={job_name="hellocron-job-dw84n"}[48h]
Content-Type: application/json

####
GET http://localhost:9090/api/v1/query?query={job_name="crontest-27930236"}[2h]
Content-Type: application/json